name: Ohm Energetics
favicon: null
layout_spectrum: 0.40808394527994096
typography_spectrum: 0.8865296428557485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5007819388993084
  lightness: 0.9671967732720077
  saturation: 0.668347553582862
  rhythmicContrast: 0.754418688826263
purpose: []
